Updated examples from source
plurimath/unicodemath-tests pull request #3
Opened 2024-02-23 15:52 UTC by suleman-uzair

This PR updates examples from source mentioned in the [file](https://github.com/plurimath/unicodemath-tests/blob/main/unicodemath_tests.yaml).

closes #2

2024-02-23 16:04 UTC, suleman-uzair commented
@ronaldtse Could you take a look at the PR and also give the access rights of the repo?
I forked it for now to create this PR.

2024-02-24 02:13 UTC, ronaldtse commented
@suleman-uzair you now have access. Thanks!

2024-02-24 02:14 UTC, ronaldtse requested changes

2024-02-24 02:14 UTC, ronaldtse commented on unicodemath_tests.yaml
> +sourced_from: https://github.com/MurrayIII/UnicodeMathML/blob/main/dist/unicodemathml-integration.js
Can we use the actual commit link because the “main” branch slides?

2024-02-26 09:55 UTC, merged

2024-02-26 09:55 UTC, ronaldtse commented
Thank you @suleman-uzair !